#!/bin/bash

# Install JupyterLab extension
jupyter labextension install @jupyterlab/toc

# Remove output from Jupyter notebooks
jupyter nbconvert --version
jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace "*.ipynb"
